import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :anoma_explorer, AnomaExplorerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production with HSTS enabled.
# Health check endpoints are excluded to allow internal HTTP health probes.
# Note `:force_ssl` is required to be set at compile-time.
config :anoma_explorer, AnomaExplorerWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    exclude: ["health", "health/ready"]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
